version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    # The actions in triage-issues.yml are updated in the Homebrew/.github repo
    ignore:
      - dependency-name: actions/stale
      - dependency-name: dessant/lock-threads
    # Disable these kinds of updates; they're handled upstream:  
    open-pull-requests-limit: 0

  - package-ecosystem: bundler
    directory: /docs
    schedule:
      interval: weekly
    allow:
      - dependency-type: all
    # Disable these kinds of updates; they're handled upstream:  
    open-pull-requests-limit: 0

  - package-ecosystem: bundler
    directory: /Library/Homebrew
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    ignore:
      - dependency-name: sorbet-runtime
    # Disable these kinds of updates; they're handled upstream:  
    open-pull-requests-limit: 0
